apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-repositories
  namespace: argocd
data:
  repositories.yaml: |
    - type: helm
      name: openbao
      url: https://openbao.github.io/openbao-helm 