nextcloud:
  host: nextcloud.example.com
  existingSecret:
    enabled: true
    secretName: examplenc-secrets
    usernameKey: nextcloud-username
    passwordKey: nextcloud-password
    tokenKey: nextcloud-token
    smtpUsernameKey: smtp-username
    smtpPasswordKey: smtp-password
    smtpHostKey: smtp-host
  persistence:
    storageClass: "example-hostpath"
  trustedDomains:
    - nextcloud.example.com
  mail:
    enabled: true
    fromAddress: noreply
    domain: example.com
    smtp:
      #host: domain.com
      secure: ssl
      port: 465
      authtype: LOGIN
  # Extra config files created in /var/www/html/config/
  # ref: https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#multiple-config-php-file
  configs:
  # For example, to enable image and text file previews:
    previews.config.php: |-
      <?php
      $CONFIG = array (
        'enable_previews' => true,
        'enabledPreviewProviders' => array (
          'OC\Preview\Movie',
          'OC\Preview\PNG',
          'OC\Preview\JPEG',
          'OC\Preview\GIF',
          'OC\Preview\BMP',
          'OC\Preview\XBitmap',
          'OC\Preview\MP3',
          'OC\Preview\MP4',
          'OC\Preview\TXT',
          'OC\Preview\MarkDown',
          'OC\Preview\PDF'
        ),
      );

    proxies.config.php: |-
      <?php
      $CONFIG = array (
        'trusted_proxies' =>
        array(
        0 => 'nextcloud.example.com',
        1 => '10.0.0.0/8',
        ),
      );

    domains.config.php: |-
      <?php
      $CONFIG = array (
        'trusted_domains' =>
        array(
        0 => 'nextcloud.example.com',
        ),
      );

    overwrite.config.php: |-
      <?php
      $CONFIG = array (
        'overwriteprotocol' => 'https'
      );
