metadata:
  name: prometheus
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kube-prometheus-stack
    repoURL: https://github.com/joshuacox/argocd-tests.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - ../example/kube-prometheus-stack/values.yaml
        - ../example/kube-prometheus-stack/secret_values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
